spring.application.name=TechSoftSolutions

# ── Puerto ──────────────────────────────────────────────────
server.port=8201
server.servlet.context-path=/sigprod

# ── MongoDB Atlas — reemplaza con tu URI real ────────────────
spring.data.mongodb.uri=mongodb+srv://enyimber1999_db_user:ZF4E5cr2M8rEJ6tz@empresariales.9bhp8wa.mongodb.net/?appName=empresariales
spring.data.mongodb.database=sigprod

# ── Thymeleaf ────────────────────────────────────────────────
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.encoding=UTF-8

# ── Logging ──────────────────────────────────────────────────
logging.level.com.techsoft.solutions=DEBUG
logging.level.org.springframework.data.mongodb=INFO
